config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :subscribers

  root 'general#home'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/general_controller.rb
class GeneralController < ApplicationController

  def home
    @subscriber = Subscriber.new
  end

end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_action :set_subscriber, only: [:show, :edit, :update, :destroy]

  # GET /subscribers
  # GET /subscribers.json
  def index
    @subscribers = Subscriber.all
  end

  # GET /subscribers/1
  # GET /subscribers/1.json
  def show
  end

  # GET /subscribers/new
  def new
    @subscriber = Subscriber.new
  end

  # GET /subscribers/1/edit
  def edit
  end

  # POST /subscribers
  # POST /subscribers.json
  def create
    @subscriber = Subscriber.new(subscriber_params)

    respond_to do |format|
      if @subscriber.save
        # format.html
        format.js { flash[:notice] = "Thanks for signing up! We'll keep you updated on our progress." }
      else
        # format.html
        format.js
      end
    end
  end

  # PATCH/PUT /subscribers/1
  # PATCH/PUT /subscribers/1.json
  def update
    respond_to do |format|
      if @subscriber.update(subscriber_params)
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscriber }
      else
        format.html { render :edit }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribers/1
  # DELETE /subscribers/1.json
  def destroy
    @subscriber.destroy
    respond_to do |format|
      format.html { redirect_to subscribers_url, notice: 'Subscriber was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscriber
      @subscriber = Subscriber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscriber_params
      params.require(:subscriber).permit(:email, :subscriber_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/general_helper.rb
module GeneralHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/layouts/_alerts_and_errors.html.erb
<!-- <div id="flash-error-messages"> -->
  <%# if flash[:notice] %>
    <!-- <p id="flash_notices" class="messages notice align center bck theme"><%#= flash[:notice] %></p> -->
    <% if flash[:notice] %>
      <script type="text/javascript">
        $(function() {
          var message = '<span id="notification-icon" class="fa fa-check-circle"></span><p><%= flash[:notice] %></p>'
          successNotification(message);
        });
      </script>
    <% end %>

    <!-- <p id="flash_errors" class="messages alert align center bck theme"><%#= flash[:alert] %></p> -->
    <% if flash[:alert] %>
      <script type="text/javascript">
        $(function() {
          var message = '<span id="notification-icon" class="fa fa-warning"></span><p><%= flash[:alert] %></p>'
          failureNotification(message);
        });
      </script>
    <% end %>
    <!-- <p id="flash_notices" class="messages notice align center bck theme">Yello</p> -->
    <!-- <p id="flash_errors" class="messages alert align center bck theme">Green</p> -->
  <%# end %>
  <%# flash[:alert] = nil %>
<!-- </div> -->


<script>
  function successNotification(message) {
    var notification = new NotificationFx({
      message : message,
      layout : 'bar',
      effect : 'slidetop',
      type : 'notice', // notice, warning or error
      onOpen : function() {
        $(".navbar-fixed-top").css({ "z-index": 0});
      },
      onClose : function() {
        $(".ns-box").slideUp('slow');
        $(".navbar-fixed-top").css({ "z-index": 1000});
        // bttn.disabled = false;
      }
    });
    notification.show();
  };

  function failureNotification(message) {
    var notification = new NotificationFx({
      message : message,
      layout : 'bar',
      effect : 'slidetop',
      type : 'notice', // notice, warning or error
      onOpen : function() {
        $(".ns-box").css({ "background": "#d25027" });
        $(".ns-effect-slidetop").css({"box-shadow": "inset 4.5em 0 #bd4823"});
        $(".navbar-fixed-top").css({ "z-index": 0});
      },
      onClose : function() {
        // $(".navbar-fixed-top").css({ "z-index": 1000});
        $(".ns-box").slideUp('slow');
        $(".navbar-fixed-top").css({ "z-index": 1000});
        // bttn.disabled = false;
      }
    });
    notification.show();
  };
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CureFunds</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- BASIC INFO -->
    <title>CureFunds</title>
    <meta name="author" content="CureFunds Inc.">
    <meta name="keywords" content="breast cancer research, cancer prevention research, clinical cancer research, aids research, cure for aids, parkinsons research, peanut allergy cure, diabetes research, juvenile diabetes research foundation, als research donation, aids cure, cure for aids, can schizophrenia be cured, cure for lupus, cure for ebola, cure for asthma">
    <meta name="description" content="Crowdfund research for cures">

    <!-- FAVICONS -->
    <link rel="icon" href="../images/favicons/favicon.ico">
    <link rel="apple-touch-icon" href="images/favicons/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="images/favicons/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="images/favicons/apple-touch-icon-114x114.png">

    <!-- CSS
    ================================= -->

    <!-- GOOGLE FONTS -->
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Montserrat:400,700">
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800">
    <link rel="stylesheet" href="//cdn.jsdelivr.net/jquery.bootstrapvalidator/0.5.0/css/bootstrapValidator.min.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/jquery.bootstrapvalidator/0.5.0/js/bootstrapValidator.min.js"></script>
  </head>
  <body class="enable-animations enable-preloader">
    <%= render 'layouts/alerts_and_errors' %>
    <%= yield %>
  </body>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-60217278-1', 'auto');
    ga('send', 'pageview');
  </script>
  <%= javascript_include_tag 'classie.js' %>
  <%= javascript_include_tag 'notificationFx.js' %>
</html>

app/views/subscribers/_form.html.erb
<%= form_for(@subscriber) do |f| %>
  <% if @subscriber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscriber.errors.count, "error") %> prohibited this subscriber from being saved:</h2>

      <ul>
      <% @subscriber.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscribers/create.js.erb
<% if @subscriber.errors.present? %>
  <% @subscriber.errors.each do |key, msg| %>
    var message = '<span id="notification-icon" class="fa fa-warning"></span><p><span id="salutation">Uh Oh!</span> Your <%= key.to_s.humanize.downcase %> <%= msg %> </p>'
    failureNotification(message);
  <% end %>
<% else %>
  // location.reload();
  var message = '<span id="notification-icon" class="fa fa-check-circle"></span><p><span id="salutation"><%= flash[:notice] %></span></p>'
  successNotification(message);
<% end %>

app/views/subscribers/edit.html.erb
<h1>Editing subscriber</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscriber %> |
<%= link_to 'Back', subscribers_path %>

app/views/subscribers/index.html.erb
<h1>Listing subscribers</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscribers.each do |subscriber| %>
      <tr>
        <td><%= subscriber.email %></td>
        <td><%= link_to 'Show', subscriber %></td>
        <td><%= link_to 'Edit', edit_subscriber_path(subscriber) %></td>
        <td><%= link_to 'Destroy', subscriber, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscriber', new_subscriber_path %>

app/views/subscribers/new.html.erb
<h1>New subscriber</h1>

<%= render 'form' %>

<%= link_to 'Back', subscribers_path %>

app/views/subscribers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @subscriber.email %>
</p>

<%= link_to 'Edit', edit_subscriber_path(@subscriber) %> |
<%= link_to 'Back', subscribers_path %>